# CMake generated Testfile for 
# Source directory: /home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples
# Build directory: /home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/cmake-cache/src/mpi/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-simple-distributed "ns3.40-simple-distributed-default")
set_tests_properties(ctest-simple-distributed PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/src/mpi/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples/CMakeLists.txt;14;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples/CMakeLists.txt;0;")
add_test(ctest-simple-distributed-mpi-comm "ns3.40-simple-distributed-mpi-comm-default")
set_tests_properties(ctest-simple-distributed-mpi-comm PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/src/mpi/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples/CMakeLists.txt;14;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples/CMakeLists.txt;0;")
add_test(ctest-nms-p2p-nix-distributed "ns3.40-nms-p2p-nix-distributed-default")
set_tests_properties(ctest-nms-p2p-nix-distributed PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/src/mpi/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples/CMakeLists.txt;14;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples/CMakeLists.txt;0;")
add_test(ctest-simple-distributed-empty-node "ns3.40-simple-distributed-empty-node-default")
set_tests_properties(ctest-simple-distributed-empty-node PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/src/mpi/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples/CMakeLists.txt;14;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples/CMakeLists.txt;0;")
add_test(ctest-third-distributed "ns3.40-third-distributed-default")
set_tests_properties(ctest-third-distributed PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/src/mpi/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples/CMakeLists.txt;27;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/src/mpi/examples/CMakeLists.txt;0;")
