# CMake generated Testfile for 
# Source directory: /home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/examples/udp-client-server
# Build directory: /home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/cmake-cache/examples/udp-client-server
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-udp-client-server "ns3.40-udp-client-server-default")
set_tests_properties(ctest-udp-client-server PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/examples/udp-client-server/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/examples/udp-client-server/CMakeLists.txt;1;build_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/examples/udp-client-server/CMakeLists.txt;0;")
add_test(ctest-udp-trace-client-server "ns3.40-udp-trace-client-server-default")
set_tests_properties(ctest-udp-trace-client-server PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/examples/udp-client-server/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/examples/udp-client-server/CMakeLists.txt;10;build_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/examples/udp-client-server/CMakeLists.txt;0;")
