# CMake generated Testfile for 
# Source directory: /home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples
# Build directory: /home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/cmake-cache/contrib/netsimulyzer/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-application-state-trace-example-netsimulyzer "ns3.40-application-state-trace-example-netsimulyzer-default")
set_tests_properties(ctest-application-state-trace-example-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;30;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-ecdf-sink-example-netsimulyzer "ns3.40-ecdf-sink-example-netsimulyzer-default")
set_tests_properties(ctest-ecdf-sink-example-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;39;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-mobility-buildings-example-netsimulyzer "ns3.40-mobility-buildings-example-netsimulyzer-default")
set_tests_properties(ctest-mobility-buildings-example-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;52;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-lena-radio-link-failure-netsimulyzer "ns3.40-lena-radio-link-failure-netsimulyzer-default")
set_tests_properties(ctest-lena-radio-link-failure-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;63;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-outdoor-random-walk-example-netsimulyzer "ns3.40-outdoor-random-walk-example-netsimulyzer-default")
set_tests_properties(ctest-outdoor-random-walk-example-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;74;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-throughput-sink-example-netsimulyzer "ns3.40-throughput-sink-example-netsimulyzer-default")
set_tests_properties(ctest-throughput-sink-example-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;85;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-bianchi-netsimulyzer "ns3.40-wifi-bianchi-netsimulyzer-default")
set_tests_properties(ctest-wifi-bianchi-netsimulyzer PROPERTIES  WORKING_DIRECTORY "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build/contrib/netsimulyzer/examples/" _BACKTRACE_TRIPLES "/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;98;build_lib_example;/home/della/drone++/src/includes/ns3/ns-allinone-3.40/ns-3.40/contrib/netsimulyzer/examples/CMakeLists.txt;0;")
